{{- if .Values.K8sBlockEndpointEditDefaultRole -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockEndpointEditDefaultRole
metadata:
  name: block-endpoint-edit-default-role
spec:
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["ClusterRole"]
    {{- if or (.Values.K8sBlockEndpointEditDefaultRole.excludeNamespaces) (hasKey .Values.K8sBlockEndpointEditDefaultRole "excludeGlobalNamespacesFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sBlockEndpointEditDefaultRole "excludeGlobalNamespacesFlag"}}
    {{- if .Values.K8sBlockEndpointEditDefaultRole.excludeGlobalNamespacesFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sBlockEndpointEditDefaultRole.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sBlockEndpointEditDefaultRole.scope}}
    scope: 
    {{.Values.K8sBlockEndpointEditDefaultRole.scope | quote -}}
    {{end -}}
{{- end -}}
