{{- if .Values.K8sDisallowedTags -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowedTags
metadata:
  name: container-image-must-not-have-latest-tag
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
    {{- if or (.Values.K8sDisallowedTags.excludeNamespaces) (hasKey .Values.K8sDisallowedTags "excludeGlobalNamespacesFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sDisallowedTags "excludeGlobalNamespacesFlag"}}
    {{- if .Values.K8sDisallowedTags.excludeGlobalNamespacesFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sDisallowedTags.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sDisallowedTags.scope}}
    scope: 
    {{.Values.K8sDisallowedTags.scope | quote -}}
    {{ end  }}
  parameters:
    tags:
     {{- range .Values.K8sDisallowedTags.parameters.tags}}
        - {{. |quote -}}
     {{ end }}
    exemptImages: 
     {{- range .Values.K8sDisallowedTags.parameters.exemptImages}}
        - {{. | quote -}}
     {{end -}}
{{- end -}}