{{- if .Values.K8sRequiredProbes -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredProbes
metadata:
  name: must-have-probes-{{.Release.Name}}
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- if or (.Values.K8sRequiredProbes.includeNamespaces) (hasKey .Values.K8sRequiredProbes "includeNamespacesDefaultFlag")}}
    {{/* Check if any specific namespaces are defined */ -}}
    namespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sRequiredProbes "includeNamespacesDefaultFlag"}}
    {{- if .Values.K8sRequiredProbes.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sRequiredProbes.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- if or (.Values.K8sRequiredProbes.excludeNamespaces) (hasKey .Values.K8sRequiredProbes "excludeGlobalNamespacesFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sRequiredProbes "excludeGlobalNamespacesFlag"}}
    {{- if .Values.K8sRequiredProbes.excludeGlobalNamespacesFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sRequiredProbes.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sRequiredProbes.scope}}
    scope: {{.Values.K8sRequiredProbes.scope | quote -}}
    {{ end }}
  parameters:
    probes: 
    {{- range .Values.K8sRequiredProbes.parameters.probes}}
      - {{. | quote -}}
    {{ end }}
    probeTypes: 
    {{- range .Values.K8sRequiredProbes.parameters.probeTypes}}
      - {{. | quote -}}
    {{ end }}
{{- end -}}