{{- if .Values.K8sRequiredLabels -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: all-must-have-owner-{{.Release.Name}}
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    {{- if or (.Values.K8sRequiredLabels.includeNamespaces) (hasKey .Values.K8sRequiredLabels "includeNamespacesDefaultFlag")}}
    {{/* Check if any specific namespaces are defined */ -}}
    namespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sRequiredLabels "includeNamespacesDefaultFlag"}}
    {{- if .Values.K8sRequiredLabels.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sRequiredLabels.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- if or (.Values.K8sRequiredLabels.excludeNamespaces) (hasKey .Values.K8sRequiredLabels "excludeGlobalNamespacesFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sRequiredLabels "excludeGlobalNamespacesFlag"}}
    {{- if .Values.K8sRequiredLabels.excludeGlobalNamespacesFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sRequiredLabels.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sRequiredLabels.scope}}
    scope: {{.Values.K8sRequiredLabels.scope | quote -}}
    {{ end }}
  parameters:
    message: "All namespaces must have an `owner` label that points to your company username"
  {{- range .Values.K8sRequiredLabels.parameters.labels}}  
    labels:
      - key: {{.key}}
        allowedRegex: {{.allowedRegex}}
  {{ end }}
{{- end -}}