{{- if .Values.K8sUniqueServiceSelector -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sUniqueServiceSelector
metadata:
  name: unique-service-selector-{{.Release.Name}}
  labels:
    owner: admin.agilebank.demo
{{- end -}}