{{- if .Values.K8sPSPAllowPrivilegeEscalationContainer -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowPrivilegeEscalationContainer
metadata:
  name: psp-allow-privilege-escalation-containers-{{.Release.Name}}
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- /* Check if any custom values are defined */ -}}
    {{- if .Values.K8sPSPAllowPrivilegeEscalationContainer}}
    {{- if or (.Values.K8sPSPAllowPrivilegeEscalationContainer.includeNamespaces) (hasKey .Values.K8sPSPAllowPrivilegeEscalationContainer "includeNamespacesDefaultFlag")}}
    {{/* Check if any specific namespaces are defined */ -}}
    namespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sPSPAllowPrivilegeEscalationContainer "includeNamespacesDefaultFlag"}}
    {{- if .Values.K8sPSPAllowPrivilegeEscalationContainer.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sPSPAllowPrivilegeEscalationContainer.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if excludeNamespaces are defined */ -}}
    {{- if or (.Values.K8sPSPAllowPrivilegeEscalationContainer.excludeNamespaces) (hasKey .Values.K8sPSPAllowPrivilegeEscalationContainer "excludeNamespacesDefaultFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sPSPAllowPrivilegeEscalationContainer "excludeNamespacesDefaultFlag"}}
    {{- if .Values.K8sPSPAllowPrivilegeEscalationContainer.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sPSPAllowPrivilegeEscalationContainer.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sPSPAllowPrivilegeEscalationContainer.scope}}
    scope: {{.Values.K8sPSPAllowPrivilegeEscalationContainer.scope | quote -}}
    {{end -}}
    {{end -}}
{{- end -}}