{{- if .Values.K8sPSPVolumeTypes -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPVolumeTypes
metadata:
  name: psp-volume-types-{{.Release.Name}}
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- /* Check if any custom values are defined */ -}}
    {{- if .Values.K8sPSPVolumeTypes}}
    {{- if or (.Values.K8sPSPVolumeTypes.includeNamespaces) (hasKey .Values.K8sPSPVolumeTypes "includeNamespacesDefaultFlag")}}
    {{/* Check if any specific namespaces are defined */ -}}
    namespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sPSPVolumeTypes "includeNamespacesDefaultFlag"}}
    {{- if .Values.K8sPSPVolumeTypes.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.includeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sPSPVolumeTypes.includeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if excludeNamespaces are defined */ -}}
    {{- if or (.Values.K8sPSPVolumeTypes.excludeNamespaces) (hasKey .Values.K8sPSPVolumeTypes "excludeNamespacesDefaultFlag")}}
    excludedNamespaces:
    {{- /* Check for globalimport include */ -}}
    {{- if hasKey .Values.K8sPSPVolumeTypes "excludeNamespacesDefaultFlag"}}
    {{- if .Values.K8sPSPVolumeTypes.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- else if .Values.globalImport.excludeNamespacesDefaultFlag}}
    {{- range .Values.globalImport.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{- range .Values.K8sPSPVolumeTypes.excludeNamespaces}}
      - {{. | quote -}}
    {{end -}}
    {{end -}}
    {{/* Check if any scope is defined (Cluster/Namespace) */ -}}
    {{- if .Values.K8sPSPVolumeTypes.scope}}
    scope: {{.Values.K8sPSPVolumeTypes.scope | quote -}}
    {{end -}}
    {{end}}
  {{- /* Check if any custom values are defined */ -}}
  {{- if hasKey .Values.K8sPSPVolumeTypes.parameters "volumes"}}
  parameters:
    volumes:
    {{- range .Values.K8sPSPVolumeTypes.parameters.volumes}}
      - {{. | quote -}}
    {{end -}}
  {{end}}
{{- end -}}